# Generated by Django 2.1.5 on 2019-01-25 09:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('iteration_type', models.IntegerField()),
                ('frequency', models.TextField(max_length=13)),
                ('object_time', models.IntegerField()),
                ('complete_day', models.IntegerField(default=0)),
                ('start_day', models.DateField(default=datetime.datetime(2019, 1, 25, 9, 43, 21, 157371, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.TextField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.TextField(max_length=30)),
                ('name', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2019, 1, 25, 9, 43, 21, 158368, tzinfo=utc))),
                ('complete_time', models.IntegerField(default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_man.Plan')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_man.User')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_man.User'),
        ),
        migrations.AlterUniqueTogether(
            name='work',
            unique_together={('user_id', 'name', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together={('user_id', 'name')},
        ),
    ]
