# Generated by Django 2.1.5 on 2019-02-03 23:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan_man', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='start_day',
            field=models.DateField(default=datetime.datetime(2019, 2, 3, 23, 46, 36, 28089, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 2, 3, 23, 46, 36, 28929, tzinfo=utc)),
        ),
    ]
